### ISSUE TITLE
这样的json生成时提示“Json格式有误”

### ISSUE THREAD

**Issue by Jungerr** [zzz40500/GsonFormat#1]
{
    "kind": "youtube#searchListResponse",
    "etag": "\"k1sYjErg4tK7WaQQxvJkW5fVrfg/usRLzp_l5ss-L8Yb9ScY-VDAEOo\"",
    "nextPageToken": "CAIQAA",
    "pageInfo": {
        "totalResults": 1000000,
        "resultsPerPage": 2
    },
    "items": [
        {
            "kind": "youtube#searchResult",
            "etag": "\"k1sYjErg4tK7WaQQxvJkW5fVrfg/D0nlqgSgFFEQnTduJtwcQZ3Hc78\"",
            "id": {
                "kind": "youtube#video",
                "videoId": "5ixFWqZGZr8"
            },
            "snippet": {
                "publishedAt": "2014-10-16T19:43:41.000Z",
                "channelId": "UC9-3c4LzdzT_HvW3Xuti9wg",
                "title": "Q&A WITH HARRY |  PRANK CALLS!",
                "description": "Can we smash 4000 likes for this Q&A!? My Flatmate Harold - http://www.youtube.com/W2S Buy Cheap and Instant Coins here: http://goo.gl/IZyNg2 Use code ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/5ixFWqZGZr8/default.jpg"
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/5ixFWqZGZr8/mqdefault.jpg"
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/5ixFWqZGZr8/hqdefault.jpg"
                    }
                },
                "channelTitle": "Calfreezy",
                "liveBroadcastContent": "none"
            }
        },
        {
            "kind": "youtube#searchResult",
            "etag": "\"k1sYjErg4tK7WaQQxvJkW5fVrfg/R5nmI-OBXmHyiXsGtMC3J6IUlBs\"",
            "id": {
                "kind": "youtube#video",
                "videoId": "8KgzATFR0As"
            },
            "snippet": {
                "publishedAt": "2014-09-03T12:49:15.000Z",
                "channelId": "UC8_yRRDIGFaJEC7NOc1qTMw",
                "title": "Harry at 30 Documentary",
                "description": "In celebration of Prince Harry's 30th birthday, ITV have released a new documentary celebrating the past three decades of his life. Featuring archive footage...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/8KgzATFR0As/default.jpg"
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/8KgzATFR0As/mqdefault.jpg"
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/8KgzATFR0As/hqdefault.jpg"
                    }
                },
                "channelTitle": "",
                "liveBroadcastContent": "none"
            }
        }
    ]
}

**Comment by zzz40500** [comment]
问题出在了default  这个字段,如果正常解析的话会是这样的  private   DefaultEntity default ;
但是在 java 中default 是关键词,关键词不能成为变量字段名,所以你要去跟服务端说,不要用 java 的关键字段当 key,希望可以帮助到你.

**Comment by Jungerr** [comment]
修改“ default”后测试可行。
谢谢，很棒的插件。
另外，这些数据是YouTube的API返回的。。。
