### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by hy200304** [zzz40500/GsonFormat#10]
插件用起来还是很方便的。就是公司代码规范里面成员变量必须加前缀m，驼峰命名。加这个功能就完美了

**Comment by zzz40500** [comment]
下版本,我给你加

**Comment by cswares** [comment]
我觉得不加更好呀。这个变量不是你生成的的吗？通过Json生成的。你Json里有就行了。

**Comment by hy200304** [comment]
多一项目选择，让用户可选

**Comment by zzz40500** [comment]
@cswares  他使用注解的形式去解析这个json,所以变量可以定制化.

**Comment by zzz40500** [comment]
在1.2 版本中已支持
