### ISSUE TITLE
关于插件把 decimal number 类型转换为 double 还是 int 的操作疑问

### ISSUE THREAD

**Issue by zhEdward** [zzz40500/GsonFormat#103]
测试用例
```json
{"TransferId":49,"ProjId":30,"ProjName":"给安卓测试","RisePercentage":0.00,"Value":60000.00,"Amount":120,"TransferTime":"2017-09-25T13:24:00.29","TradeDate":"2017-09-25","TransferStatus":3,"TransferStatusTxt":"已终止"}
```

插件版本（README.md 可能要更新下说明）
![image](https://user-images.githubusercontent.com/12438329/31304955-0c218538-aaf4-11e7-9190-873a4e1f83cc.png)

问题：使用插件，如果没点击右上角的 <kbd>Format</kbd> 直接转换 ，json中的 `RisePercentage` `Value` 可以被正确识别成我所期望的 double类型，但凡点击了 <kbd>Format</kbd> 这两个字段已被转变为了 0 和 60000 的 int 类型（虽然此时可以开启`vrigo mode` 手动修正），这个算是bug还是 插件机制决定就是这样子的呢？

**Comment by zzz40500** [comment]
这个bug ,具体原因是因为使用org.json.JSONObject  这个会在下个版本修复
