### ISSUE TITLE
如果 .AndroidStudio 配置文件夹迁移到D盘，则GsonFormat插件无法安装

### ISSUE THREAD

**Issue by hanshou101** [zzz40500/GsonFormat#115]
1.
之前为了节省C盘磁盘空间，把  .AndroidStudio 文件夹，迁移到了D盘下面
idea.config.path=D:\AndroidStudioWorkSpace\.AndroidStudio3.0\config
idea.system.path=D:\AndroidStudioWorkSpace\.AndroidStudio3.0\system

2.
然后，
发现从Android Studio的 plugin repositories 里面找到的【GsonFormat】，无法安装。（提示重启AS，重启后不报错，但plugin列表里，GsonFormat也没有安装上去）

3.
而且，
先下载  GsonFormat.jar，
再从本地磁盘  from disk  手动安装，也无法安装上【GsonFormat】。（提示重启AS，重启后无报错，但plugin列表里，GsonFormat没有安装上去）

4.
将  .AndroidStudio  文件夹，迁移回C盘。
发现可以成功安装  【GsonFormat】  了。

**Comment by hanshou101** [comment]
这个问题，

是我自身的操作问题，
还是Google  AS的机制问题，
还是GsonFormat的插件默认配置问题呢？

**Comment by DimRed** [comment]
只能说跟 GsonFormat 默认配置 无关,  应该是AS 的机制问题.

**Comment by voidzero42** [comment]
正常AS的插件会下到/system/plugins里面,安装完zip包会解压(jar包直接复制)到/config/plugins里面.
如果改了默认地址,就需要手动从system复制到config里面,
重启AS就行了.
