### ISSUE TITLE
能将符合日期格式的Field,识别出Date类型吗?

### ISSUE THREAD

**Issue by acdsee3003** [zzz40500/GsonFormat#12]
常用的日期格式:2015/8/5 10:12 , 2015-8-5 10:12 类似这样的,现在识别出的是String,能识别出Date类型吗? 或者提供一个配置来设置这些解析格式?

**Comment by zzz40500** [comment]
不支持对 Date 类型的解析,暂时只支持 JSONObject 能解析的类型
