### ISSUE TITLE
生成出错

### ISSUE THREAD

**Issue by lydlovezjr** [zzz40500/GsonFormat#130]
<img width="517" alt="_20190308104503" src="https://user-images.githubusercontent.com/19246347/54004161-880a0e80-418f-11e9-9afe-60ac37728668.png">
<img width="597" alt="_20190308104537" src="https://user-images.githubusercontent.com/19246347/54004167-8b9d9580-418f-11e9-8917-938f19eee443.png">

**Comment by gejun123456** [comment]
插件无法判断你字符串中的 null 是什么类型，把null 改成 你想要类型的值 应该就好了
