### ISSUE TITLE
[1,2,3,4] generates List<int>

### ISSUE THREAD

**Issue by pdavid0** [zzz40500/GsonFormat#14]
```
{ "list": [1,2,3,4] }
```
generates 
```
List<int> list;
```
It should generate a 
```
List<Integer> list;
```

Thanks for this great plugin, it saved me a lot of time ! 非常感谢

**Comment by zzz40500** [comment]
Thanks , I will fix it as soon as possible.

**Comment by zzz40500** [comment]
Fixed in version 1.2
