### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by kevin-duan** [zzz40500/GsonFormat#15]
{
      "id": "10",
      "tid": "B-12",
      "remark": "备注",
      "request_time": "July 31,2015 am 12:00",
      "type": "3"
    }
像这样格式的json request_time 这个key值生成的时候变成RequestTime 这样的形式，怎样变成Request_time这种形式

**Comment by zzz40500** [comment]
不支持对 Date 类型的解析,暂时只支持 JSONObject 能解析的类型
