### ISSUE TITLE
建议增加可以设置成员变量前缀的功能，比如m前缀

### ISSUE THREAD

**Issue by qianhk** [zzz40500/GsonFormat#17]
最好可以读取设置-》coding style -》 java-》code generation里面的设置，field name prefix。

**Comment by zzz40500** [comment]
ok, 纳入下个版本的更新内容中

**Comment by qianhk** [comment]
非常感谢，再提示下: 比如成员变量是 int mCount;   那么get方法是 getCount，而不是getmCount哦。
另外最好再加两个打勾的设置，设置要get 还是set方法，一般从网络读取json数据后只要get方法，不需要set方法。这样需要get就打勾get，也是需要set就打勾set，都要就都打勾。

**Comment by zzz40500** [comment]
已经更新到1.2.0 支持Field Name 前缀 设置优先从设置获取,暂不支持 set 和 get 的方法的选择
