### ISSUE TITLE
继成员变量前缀m支持的后续

### ISSUE THREAD

**Issue by qianhk** [zzz40500/GsonFormat#18]
上次提了个增加成员变量前缀m的支持，新版本已经支持了，感谢作者，那么问题来了，既然有m前缀了，能否再进一步改进下，当用了前缀的时候：如下两个问题：
举个例子
public void setUrl(String Url) {
        this.mUrl = Url;
    }
1.set方法的this.mXXX=XXX，将this. 去掉，因为成员变量名已经与方法参数名字不一样了，不需要this区分了。
2.方法参数的变量首字母小写Url -> url
最后变成
public void setUrl(String url) {
        mUrl = url;
    }

再举个例子：
public void setTypeDescription(String TypeDescription) {
        this.mTypeDescription = TypeDescription;
    }
变成：
public void setTypeDescription(String typeDescription) {
        mTypeDescription = typeDescription;
    }

**Comment by zzz40500** [comment]
this 我觉得挺好的没必要去掉. 变量首字母小写Url -> url这个是我的测试不到位的问题,同时也是因为我比较懒呀. 不过我一般喜欢用 public 修饰.
