### ISSUE TITLE
这个json解析错误

### ISSUE THREAD

**Issue by waysnotes** [zzz40500/GsonFormat#19]
{
    "data": {
        "list": [
            {
                "stylists": [
                    {
                        "stylist_id": "100",
                        "name": "赵元",
                        "nickname": "赵元",
                        "head_icon": "http://7xl734.com1.z0.glb.clouddn.com/1.png",
                        "list_img": "http://7xl734.com1.z0.glb.clouddn.com/1.1.png\r\n",
                        "phone": "***********",
                        "city": "",
                        "city_name": null,
                        "areas": [
                            null
                        ],
                        "aois": [
                            null
                        ],
                        "star_level": "5",
                        "title": "大咖",
                        "tags": [
                            "时尚大师，偶像全能，百搭达人"
                        ]
                    },
                    {
                        "stylist_id": "101",
                        "name": "张书平",
                        "nickname": "张书平",
                        "head_icon": "http://7xl734.com1.z0.glb.clouddn.com/2.png",
                        "list_img": "http://7xl734.com1.z0.glb.clouddn.com/2.1.png",
                        "phone": "***********",
                        "city": "",
                        "city_name": null,
                        "areas": [
                            null
                        ],
                        "aois": [
                            null
                        ],
                        "star_level": "5",
                        "title": "总监",
                        "tags": [
                            "时尚前卫，颜值爆表，造星\r\n"
                        ]
                    },
                    {
                        "stylist_id": "102",
                        "name": "张荣辉",
                        "nickname": "张荣辉",
                        "head_icon": "http://7xl734.com1.z0.glb.clouddn.com/3.png",
                        "list_img": "http://7xl734.com1.z0.glb.clouddn.com/3.1.png",
                        "phone": "***********",
                        "city": "",
                        "city_name": null,
                        "areas": [
                            null
                        ],
                        "aois": [
                            null
                        ],
                        "star_level": "5",
                        "title": "总监",
                        "tags": [
                            "色彩大师，时尚造型，烫染达人\r\n"
                        ]
                    },
                    {
                        "stylist_id": "103",
                        "name": "谢谊",
                        "nickname": "谢谊",
                        "head_icon": "http://7xl734.com1.z0.glb.clouddn.com/4.png",
                        "list_img": "http://7xl734.com1.z0.glb.clouddn.com/4.1.png",
                        "phone": "***********",
                        "city": "",
                        "city_name": null,
                        "areas": [
                            null
                        ],
                        "aois": [
                            null
                        ],
                        "star_level": "4",
                        "title": "资深",
                        "tags": [
                            "时尚大师，偶像全能，百搭达人\r\n"
                        ]
                    },
                    {
                        "stylist_id": "104",
                        "name": "付军",
                        "nickname": "付军",
                        "head_icon": "http://7xl734.com1.z0.glb.clouddn.com/5.png",
                        "list_img": "http://7xl734.com1.z0.glb.clouddn.com/5.1.png",
                        "phone": "***********",
                        "city": "",
                        "city_name": null,
                        "areas": [
                            null
                        ],
                        "aois": [
                            null
                        ],
                        "star_level": "5",
                        "title": "大咖",
                        "tags": [
                            "时尚前卫，颜值爆表，造星\r\n"
                        ]
                    },
                    {
                        "stylist_id": "105",
                        "name": "房恩新",
                        "nickname": "房恩新",
                        "head_icon": "http://7xl734.com1.z0.glb.clouddn.com/6.png",
                        "list_img": "http://7xl734.com1.z0.glb.clouddn.com/6.1.png",
                        "phone": "***********",
                        "city": "",
                        "city_name": null,
                        "areas": [
                            null
                        ],
                        "aois": [
                            null
                        ],
                        "star_level": "4",
                        "title": "资深",
                        "tags": [
                            "色彩大师，时尚造型，烫染达人\r\n"
                        ]
                    },
                    {
                        "stylist_id": "106",
                        "name": "陈晓松",
                        "nickname": "陈晓松",
                        "head_icon": "http://7xl734.com1.z0.glb.clouddn.com/7.png",
                        "list_img": "http://7xl734.com1.z0.glb.clouddn.com/7.1.png",
                        "phone": "***********",
                        "city": "",
                        "city_name": null,
                        "areas": [
                            null
                        ],
                        "aois": [
                            null
                        ],
                        "star_level": "4.5",
                        "title": "无",
                        "tags": [
                            "时尚前卫，颜值爆表，造星\r\n"
                        ]
                    }
                ],
                "stylist_tab_tag": "实力派艺人",
                "stylist_tag_alias": "strength star",
                "total_stylist": 7
            },
            {
                "stylists": [
                    {
                        "stylist_id": "100",
                        "name": "赵元",
                        "nickname": "赵元",
                        "head_icon": "http://7xl734.com1.z0.glb.clouddn.com/1.png",
                        "list_img": "http://7xl734.com1.z0.glb.clouddn.com/1.1.png\r\n",
                        "phone": "***********",
                        "city": "",
                        "city_name": null,
                        "areas": [
                            null
                        ],
                        "aois": [
                            null
                        ],
                        "star_level": "5",
                        "title": "大咖",
                        "tags": [
                            "时尚大师，偶像全能，百搭达人"
                        ]
                    },
                    {
                        "stylist_id": "101",
                        "name": "张书平",
                        "nickname": "张书平",
                        "head_icon": "http://7xl734.com1.z0.glb.clouddn.com/2.png",
                        "list_img": "http://7xl734.com1.z0.glb.clouddn.com/2.1.png",
                        "phone": "***********",
                        "city": "",
                        "city_name": null,
                        "areas": [
                            null
                        ],
                        "aois": [
                            null
                        ],
                        "star_level": "5",
                        "title": "总监",
                        "tags": [
                            "时尚前卫，颜值爆表，造星\r\n"
                        ]
                    },
                    {
                        "stylist_id": "102",
                        "name": "张荣辉",
                        "nickname": "张荣辉",
                        "head_icon": "http://7xl734.com1.z0.glb.clouddn.com/3.png",
                        "list_img": "http://7xl734.com1.z0.glb.clouddn.com/3.1.png",
                        "phone": "***********",
                        "city": "",
                        "city_name": null,
                        "areas": [
                            null
                        ],
                        "aois": [
                            null
                        ],
                        "star_level": "5",
                        "title": "总监",
                        "tags": [
                            "色彩大师，时尚造型，烫染达人\r\n"
                        ]
                    },
                    {
                        "stylist_id": "103",
                        "name": "谢谊",
                        "nickname": "谢谊",
                        "head_icon": "http://7xl734.com1.z0.glb.clouddn.com/4.png",
                        "list_img": "http://7xl734.com1.z0.glb.clouddn.com/4.1.png",
                        "phone": "***********",
                        "city": "",
                        "city_name": null,
                        "areas": [
                            null
                        ],
                        "aois": [
                            null
                        ],
                        "star_level": "4",
                        "title": "资深",
                        "tags": [
                            "时尚大师，偶像全能，百搭达人\r\n"
                        ]
                    },
                    {
                        "stylist_id": "104",
                        "name": "付军",
                        "nickname": "付军",
                        "head_icon": "http://7xl734.com1.z0.glb.clouddn.com/5.png",
                        "list_img": "http://7xl734.com1.z0.glb.clouddn.com/5.1.png",
                        "phone": "***********",
                        "city": "",
                        "city_name": null,
                        "areas": [
                            null
                        ],
                        "aois": [
                            null
                        ],
                        "star_level": "5",
                        "title": "大咖",
                        "tags": [
                            "时尚前卫，颜值爆表，造星\r\n"
                        ]
                    },
                    {
                        "stylist_id": "105",
                        "name": "房恩新",
                        "nickname": "房恩新",
                        "head_icon": "http://7xl734.com1.z0.glb.clouddn.com/6.png",
                        "list_img": "http://7xl734.com1.z0.glb.clouddn.com/6.1.png",
                        "phone": "***********",
                        "city": "",
                        "city_name": null,
                        "areas": [
                            null
                        ],
                        "aois": [
                            null
                        ],
                        "star_level": "4",
                        "title": "资深",
                        "tags": [
                            "色彩大师，时尚造型，烫染达人\r\n"
                        ]
                    },
                    {
                        "stylist_id": "106",
                        "name": "陈晓松",
                        "nickname": "陈晓松",
                        "head_icon": "http://7xl734.com1.z0.glb.clouddn.com/7.png",
                        "list_img": "http://7xl734.com1.z0.glb.clouddn.com/7.1.png",
                        "phone": "***********",
                        "city": "",
                        "city_name": null,
                        "areas": [
                            null
                        ],
                        "aois": [
                            null
                        ],
                        "star_level": "4.5",
                        "title": "无",
                        "tags": [
                            "时尚前卫，颜值爆表，造星\r\n"
                        ]
                    }
                ],
                "stylist_tab_tag": "全能型艺人",
                "stylist_tag_alias": "universal star",
                "total_stylist": 7
            }
        ],
        "total": 2
    },
    "errno": 0,
    "errmsg": ""
}

**Comment by waysnotes** [comment]
不知道是什么情况导致的？

**Comment by zzz40500** [comment]
我的问题  晚上给你解决

**Comment by zzz40500** [comment]
定位到问题了"list_img": "http://7xl734.com1.z0.glb.clouddn.com/1.1.png\r\n",  有个\ r  
写入注释的时候导致ide 对换行认知出现了问题.

**Comment by waysnotes** [comment]
确实是符号的问题，去掉就好了   谢谢

**Comment by zzz40500** [comment]
下个版本会过滤这种情况
