### ISSUE TITLE
变量类型不能修改的问题

### ISSUE THREAD

**Issue by SharerMax** [zzz40500/GsonFormat#21]
版本1.2.0
从json数据装换为实体类时不能修改成员变量的类型，成员变量名可以修改

**Comment by zzz40500** [comment]
支持内部类名更改，不支持基本类型的修改，因为我怕你们改坏😂.

**Comment by SharerMax** [comment]
...
因为遇到一些json数据，某些字段暂时是没有值的会直接返回一个null，但是这个字段的值后续会添加，所以才有了这个需求。。

**Comment by zzz40500** [comment]
其实我推荐的是 json 中的尽量有都有值,这样生成的实体类才比较全.
然后说说你这个情况.返回 null 的话说明这是个一个对象,对象对应的这里是 Object ,
后面升级的话,即使可以更改的话,也只是将 Object 可以改成 String,但是不能改成基本数据类型.也不能改成实体类.

现有的建议:
如果是在第一级的属性为 null, 后面可能会添加的话,建议是先不主动生成.
等后面值已经出来以后的话,你在使用 Gsonformat 的生成,它是支持已存在一级属性和父类属性的过滤的.

**Comment by SharerMax** [comment]
也只能这样了   谢谢

**Comment by zzz40500** [comment]
等我有空.把这个加进去.

**Comment by xiaolongyuan** [comment]
额  “支持内部类名更改，不支持基本类型的修改，因为我怕你们改坏😂.” 什么意思

**Comment by zzz40500** [comment]
怕把 int类型的改成 String ,有或者 String 改成 Strin  .

**Comment by yemengsky** [comment]
其实主要是 long类型的数据总是被解释为int型，还是可以修改的比较好。

**Comment by xiaolongyuan** [comment]
@zzz40500 改错了就直接报错好了 或者直接就生成错误的 作为开发者 这点常识还是有的吧 int 变量类型不能改 真的很烦

**Comment by zzz40500** [comment]
int  和 long 呀.
行,下版本开放这方面的修改.

**Comment by xiaolongyuan** [comment]
如此便是极好的

**Comment by f839903061** [comment]
@zzz40500  我遇到的一个特别小的有关变量类型问题：json里面的数据有一个价格是0.1元，使用插件自动转换的时候，把这个价格指定的确是int类型，无法修改为float类型！所以我这边一直拿到的数据都是0元，而不是正确的0.1元！目前我是自动生成Bean之后，再手动修改int 为float !其他的没什么了，用着真的是很方便

**Comment by ipcjs** [comment]
改坏了的话IDE会报错的吧，感觉还是开放改好一点(-_-#)
