### ISSUE TITLE
Variable name depends on type

### ISSUE THREAD

**Issue by Swisyn** [zzz40500/GsonFormat#22]
Hey i've been using this plugin since it's released, thank you for developing and improving it.

Could you make an option the change prefix of variable name? Such as boolean types of variables generally starting with is (isSuccess, isGenerated etc.) but the plugin generates getSuccess which is not well i think.

Thank you.

**Comment by zzz40500** [comment]
Thank you for your feedback, I will fix as soon as possible

**Comment by Swisyn** [comment]
Thank you @zzz40500
