### ISSUE TITLE
变量名自动变驼峰法的建议

### ISSUE THREAD

**Issue by ikidou** [zzz40500/GsonFormat#24]
Hello，部分API返回的字段名使用的是下划线分格（PHP），但Java一段使用的是驼峰法，如果一个一个改的话，太麻烦了，可否自动转换成驼峰法，毕竟增删字段的时候，又要重来，不然代码看起来不爽，希望可以加入。

**Comment by zzz40500** [comment]
已经支持了.setting-> use serializedName  勾上就可以自动转换成驼峰了.

**Comment by ikidou** [comment]
好吧，这个真看不出，以为只是全部加上SerializedName注解呢,3Q
