### ISSUE TITLE
以Map的Key值为名字的Json解析出错

### ISSUE THREAD

**Issue by chihochow** [zzz40500/GsonFormat#29]
错误提示：
 com.intellij.util.IncorrectOperationException: Incorrect field '/** 
* stock : 20
* salePrice : 219.45
*/ 
private  20509:28314;1627207:28338Entity 20509:28314;1627207:28338 ; 

=================================

解析字段如下：
{
  "skuMap": {
    "20509:28314;1627207:28338": {
      "stock": 20,
      "salePrice": 219.45
    }
  }
}

**Comment by zzz40500** [comment]
因为你的key 是纯数字, 开启前缀就可以了
