### ISSUE TITLE
数据类型无法修改

### ISSUE THREAD

**Issue by start141** [zzz40500/GsonFormat#32]
首先感谢作者提供了这么便捷好用的插件！

#21 据说作者是因为怕数据类型被改错而没有提供修改数据类型的功能。

但是我目前就遇到了int转long、int转String、int转float、int转double的问题。

所以还是请求大大加一个修改变量数据类型的功能，谢谢啦！

**Comment by zzz40500** [comment]
好的,最近添加这个 feature
