### ISSUE TITLE
Add LoganSquare

### ISSUE THREAD

**Issue by Swisyn** [zzz40500/GsonFormat#34]
Hi, this plugin is great. Would you please add the LoganSquare annotation? It would be great, its more faster than the gson.
https://github.com/bluelinelabs/LoganSquare

https://github.com/bluelinelabs/LoganSquare/blob/master/docs/AnnotationsOnlyModel.md

**Comment by zzz40500** [comment]
i will add in next version.

**Comment by Swisyn** [comment]
@zzz40500 thank you so much
