### ISSUE TITLE
cannot handle json value with '//' (不能处理带'//'的值)

### ISSUE THREAD

**Issue by houfukude** [zzz40500/GsonFormat#4]
最近正好在用Gson开发 ，很不错的小工具！
刚刚试了下这样的json无法处理~

    {
        "r":0,                      
        "err":"None",               
        "photo":"http://xxxx.com/photo.jpg"
    }

**Comment by zzz40500** [comment]
ok，晚上的时候发修复包

**Comment by zzz40500** [comment]
已更新1.1.1
