### ISSUE TITLE
设置页面显示不全

### ISSUE THREAD

**Issue by ichenkaihua** [zzz40500/GsonFormat#42]
版本:1.2.2
as版本:2.0-beta7
分辨率 1920*1080 14寸
表现:
打开gsonformat，点击setting,setting对话框不能拉伸宽度高度（底部有部分设置选项没有显示）

**Comment by zzz40500** [comment]
ok , 我看看

**Comment by tanranran** [comment]
版本 1.2.3 
AS版本 2.2  preview1
我也是。。。 1920*1080 17寸
打开gsonformat  setting  保存按钮看不到。

**Comment by zzz40500** [comment]
@ichenkaihua  最新版本还有这个问题吗？

**Comment by ichenkaihua** [comment]
@zzz40500 现在换电脑了，在21寸 1600*900 上是正常的
