### ISSUE TITLE
可不可以加一个选择get/set的选项

### ISSUE THREAD

**Issue by cwenlu** [zzz40500/GsonFormat#46]
因为移动端的原因，我一般都是直接public的，不用get/set

**Comment by xiaolongyuan** [comment]
+1

**Comment by zzz40500** [comment]
已支持, 查看设置, 将 Field 选择 public 就可以了

**Comment by cwenlu** [comment]
thx
----- 原始邮件 -----
发件人：轻微 <notifications@github.com>
收件人：zzz40500/GsonFormat <GsonFormat@noreply.github.com>
抄送人：cwenlu <cwenlu@sina.cn>,  Author <author@noreply.github.com>
主题：Re:_[zzz40500/GsonFormat]_可不可以加一个选择get/set的选项_(#46)
日期：2016年06月01日 07点48分

已支持, 查看设置, 将 Field 选择 public 就可以了

&mdash;
