### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by jtyang** [zzz40500/GsonFormat#5]
建议有选择能生成：字段是public的，不要private和提供get/set方法了；
毕竟在android上不太建议使用get/set

**Comment by zzz40500** [comment]
没有听说Android 不建议使用 get/set 方法?

**Comment by yrom** [comment]
http://developer.android.com/training/articles/perf-tips.html#GettersSetters

**Comment by zzz40500** [comment]
@yrom  谢谢你的连接

**Comment by zzz40500** [comment]
@jtyang 版本升级到1.1.2就可以手动设置字段为public 替代 private 和 get/set 方法.默认是 private 的模式
