### ISSUE TITLE
AutoValue支持

### ISSUE THREAD

**Issue by pkliang** [zzz40500/GsonFormat#53]
你好，可否加入对AutoValue的支持，生成AutoValue风格的java code，谢谢。

**Comment by gengjiawen** [comment]
I create a pr for this https://github.com/zzz40500/GsonFormat/pull/57.
You can download the jar to try it. Have fun.

**Comment by pkliang** [comment]
Awesome, thanks dude!

**Comment by gengjiawen** [comment]
@pkliang Please in setting check `filed(public)` when want to use autovalue.It's bug I find this afternoon.I will try to fix it as soon as possiable.

**Comment by gengjiawen** [comment]
fixed via https://github.com/zzz40500/GsonFormat/pull/60

**Comment by zzz40500** [comment]
感谢@gengjiawen 的集成。 我已经发布到intellij 的plugin 仓库中，你可以升级试试看。

**Comment by gengjiawen** [comment]
:)
