### ISSUE TITLE
Migrate project to gradle

### ISSUE THREAD

**Issue by gengjiawen** [zzz40500/GsonFormat#58]
Now we have https://github.com/JetBrains/gradle-intellij-plugin.
Any plan to migrate current project to Gradle build system?
Without gradle, project import and many other things is realy tedious and error prone.

**Comment by zzz40500** [comment]
I don't have such a plan yet.

**Comment by zzz40500** [comment]
PR welcomed ;)

**Comment by gengjiawen** [comment]
I create a pr for this feature.Will you take a look at https://github.com/zzz40500/GsonFormat/pull/59 ?

**Comment by zzz40500** [comment]
You're amazing! @gengjiawen
