### ISSUE TITLE
2个小建议

### ISSUE THREAD

**Issue by houfukude** [zzz40500/GsonFormat#6]
1.搜索当前extends和implements，不创建已经在父类中创建了的参数以及 get/set 方法
2.搜索当前目录（或者子目录也带上？) 如果已有的类中的变量和需要创建的内部类匹配就直接使用那个类

**Comment by echan0524** [comment]
Anyway to generate based on prefix such as 'm'.  For example, mName, mAge for private variables?

**Comment by zzz40500** [comment]
1.1.3 版本会遍历父类的已有的属性,不会重复生成相同属性,在使用了SerializedName,会对属性进行驼峰格式化.会遍历父类拥有的实体类.复用实体类,基于轻量工具的思想,并不会让他遍历当前目录或是子目录.因为这样可能会使他占用大量的资源,或则更耗时.

**Comment by zzz40500** [comment]
@echan0524  I think prefix is unnecessary for entity class
