### ISSUE TITLE
能支持auto-value-gson吗?

### ISSUE THREAD

**Issue by bu2zhouzhu** [zzz40500/GsonFormat#66]
[auto-value-gson](https://github.com/rharter/auto-value-gson)

**Comment by zzz40500** [comment]
支持[AutoValue](https://github.com/google/auto/tree/master/value)  这个应该也可以。

**Comment by gengjiawen** [comment]
1.3.0 已经支持了

**Comment by bu2zhouzhu** [comment]
@gengjiawen 怎么设置呢？我现在在Android Studio中按Alt+S打开GsonFormat对话框粘贴json进去点击OK按钮生成的是JavaBean规范的类．而不是AutoValue规范的类．

**Comment by bu2zhouzhu** [comment]
@gengjiawen 我找到了．在Setting最下方Convert Library中有AutoValue选项．选择这个后生成的就是AutoValue规范的类了．

**Comment by gengjiawen** [comment]
嗯,可能不太好找,后续改善文档
