### ISSUE TITLE
支持复制粘贴吗？

### ISSUE THREAD

**Issue by HanderWei** [zzz40500/GsonFormat#7]
IDE: Android Studio 1.2.2
MacBook Pro 

无法复制粘贴

一定要手动输入？我看到截图上应该是复制粘贴的吧

**Comment by zzz40500** [comment]
支持，手输就太鸡肋了

**Comment by HanderWei** [comment]
@zzz40500 秒回啊...
我知道为什么不能粘贴了
我改了Mac `粘贴`的快捷键，您做的插件是默认按键

非常感谢！
