### ISSUE TITLE
Hidpi support in setting window

### ISSUE THREAD

**Issue by gengjiawen** [zzz40500/GsonFormat#70]
In  windows 4k display, the setting dialog is not showing right. And it can't be expand when drag bottom right corner.

![2016-12-08_103842](https://cloud.githubusercontent.com/assets/3759816/20995522/9d61232e-bd32-11e6-92d3-7a868983cc1c.png)

**Comment by yubinghuang** [comment]
1920*1080 have same question

**Comment by gengjiawen** [comment]
Maybe we can unlock the resizable attribute

**Comment by zzz40500** [comment]
fixed in version  1.5.0
