### ISSUE TITLE
找不到 org.org.json.JSONObject

### ISSUE THREAD

**Issue by kolyneh** [zzz40500/GsonFormat#75]
public  static $ClassName$ objectFromData(String str, String key){
        try {
            org.org.json.JSONObject jsonObject=new org.org.json.JSONObject(str);
            return new com.google.gson.Gson().fromJson(jsonObject.getString(str),$ClassName$.class);
        } catch (org.org.json.JSONException e) {
            e.printStackTrace();
        }
        return null;
    }
是org.json.JSONObject吧

**Comment by zzz40500** [comment]
这一块可以直接改.

**Comment by kolyneh** [comment]
好的，辛苦了



-------- 原始邮件 --------
发件人：轻微 <notifications@github.com>
时间：周六 12月17日 00:06
收件人：zzz40500/GsonFormat <GsonFormat@noreply.github.com>
抄送：kolyneh <wannagowithu@live.com>,Author <author@noreply.github.com>
主题：Re: [zzz40500/GsonFormat] 找不到 org.org.json.JSONObject (#75)


这一块可以直接改.

**Comment by zzz40500** [comment]
下版本 ,马上改.

**Comment by zzz40500** [comment]
1.50 修复了
