### ISSUE TITLE
你好，我自己写插件出了点问题，在AndroidStudio中崩溃，请问怎么解决？

### ISSUE THREAD

**Issue by Ayvytr** [zzz40500/GsonFormat#92]

**Comment by zzz40500** [comment]
JDK 换成1.6 的兼容模式试试, 不行, 你发邮件给我吧.

**Comment by Ayvytr** [comment]
哈喽！

附件是我的工程。

还有一个问题，配置gradle依赖是Android Studio必须的？我看了网上很多的插件，都没有配置gradle依赖，直接用 idea 写了就能用了。但是我写出来的插件，在As里头崩溃。。。头疼。还有怎么让idea和As的插件搜索中搜出来我的插件？

或者用qq微信联系？


发自网易邮箱大师

在2017年06月14日 22:55，轻微<notifications@github.com><mailto:notifications@github.com> 写道：

JDK 换成1.6 的兼容模式试试, 不行, 你发邮件给我吧.

**Comment by Ayvytr** [comment]
ignore
