### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by 79660095** [zzz40500/GsonFormat#96]
现在1.5版本 在生成的内部类默认都自带了static修饰，感觉这个没有必要呀。还是可以在哪里设置的求指点。 我在界面的引用了带static 修饰的类  因为是静态类  这样会不会回收的可能性会提高呢。

**Comment by zzz40500** [comment]
这里使用static 修饰, 是为了让这个类可以独立与它所在的类的影响, 意思就是你可以单独new出static 修饰的类, 如果不用static 修饰, 你要使用这个类的时候,需要先new 这个类所在的类. 这个是没有必要的.
