### ISSUE TITLE
请教一下 怎么让这个插件能生成map类型的变量呢

### ISSUE THREAD

**Issue by zohar-soul** [zzz40500/GsonFormat#97]
我的意思是。比如这么一个json

> {
    "attachs": {
        "0": {
            "attachurl": "mon_201707/25/c4Qho6-kpukKkT1kSfa-r6.jpg",
            "size": 21,
            "type": "img",
            "subid": 0,
            "url_utf8_org_name": "2%2ejpg",
            "dscp": "",
            "path": "mon_201707/25",
            "name": "c4Qho6-kpukKkT1kSfa-r6.jpg",
            "ext": "jpg",
            "thumb": 56
        },
        "1": {
            "attachurl": "mon_201707/25/c4Qho6-2180KqT1kSfa-dc.jpg",
            "size": 26,
            "type": "img",
            "subid": 1,
            "url_utf8_org_name": "1%2ejpg",
            "dscp": "",
            "path": "mon_201707/25",
            "name": "c4Qho6-2180KqT1kSfa-dc.jpg",
            "ext": "jpg",
            "thumb": 56
        }
    }
}

他生成的时候会生成为这种样式

> private AttachsBean attachs;
    
    public static class AttachsBean {
        @SerializedName("0")
        private _$0Bean _$0;
        @SerializedName("1")
        private _$1Bean _$1;
        
        ...

        public static class _$0Bean {
            private String attachurl;
            private int size;
            private String type;
            private int subid;
            private String url_utf8_org_name;
            private String dscp;
            private String path;
            private String name;
            private String ext;
            private int thumb;
        }

        public static class _$1Bean {
            private String attachurl;
            private int size;
            private String type;
            private int subid;
            private String url_utf8_org_name;
            private String dscp;
            private String path;
            private String name;
            private String ext;
            private int thumb;
            ....
        }
    }
但是其实生成为这样的就可以了 

>     public static class AttachsBean {

        private Map<String,Content> map;

        ...

        public static class Content {
            private String attachurl;
            private int size;
            private String type;
            private int subid;
            private String url_utf8_org_name;
            private String dscp;
            private String path;
            private String name;
            private String ext;
            private int thumb;
        }

    }

有什么办法来做到嘛 谢谢啦

**Comment by zzz40500** [comment]
还没有很好的办法处理这个case
